import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import * as S from "../src/styles";

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Main>
        <S.Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </S.Title>

        <S.Description>
          Get started by editing <S.Code>pages/index.tsx</S.Code>
        </S.Description>

        <S.Grid>
          <S.Card href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </S.Card>

          <S.Card href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </S.Card>

          <S.Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </S.Card>

          <S.Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </S.Card>
        </S.Grid>
      </S.Main>

      <S.Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <S.Logo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </S.Logo>
        </a>
      </S.Footer>
    </S.Container>
  );
};

export default Home;
