import type { GetStaticProps, NextPage } from "next";
import * as S from "../src/styles";

//hooks
import { useTranslations } from "next-intl";

//components
import Head from "next/head";
import Image from "next/image";

//this function is necessary to get the translations in every single page
export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      messages: (await import(`../public/locales/${locale}.json`)).default,
    },
  };
};

const Home: NextPage = () => {
  const t = useTranslations("common");

  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Main>
        <S.Title>
          {t("welcome")} <a href="https://nextjs.org">{t("nextjs")}!</a>
        </S.Title>

        <S.Description>
          {t("get_started")} <S.Code>pages/index.tsx</S.Code>
        </S.Description>

        <S.Grid>
          <S.Card href="https://nextjs.org/docs">
            <h2>{t("documentation")} &rarr;</h2>
            <p>{t("documentation_description")}</p>
          </S.Card>

          <S.Card href="https://nextjs.org/learn">
            <h2>{t("learn")} &rarr;</h2>
            <p>{t("learn_description")}</p>
          </S.Card>

          <S.Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>{t("exemples")} &rarr;</h2>
            <p>{t("exemples_description")}</p>
          </S.Card>

          <S.Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>{t("deploy")} &rarr;</h2>
            <p>{t("deploy_description")}</p>
          </S.Card>
        </S.Grid>
      </S.Main>

      <S.Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <S.Logo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </S.Logo>
        </a>
      </S.Footer>
    </S.Container>
  );
};

export default Home;
